//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.20 at 04:07:50 PM CST 
//


package org.shaolin.bmdp.datamodel.page;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FontStyleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FontStyleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Plain"/>
 *     &lt;enumeration value="Bold"/>
 *     &lt;enumeration value="Italic"/>
 *     &lt;enumeration value="Bold Italic"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FontStyleType")
@XmlEnum
public enum FontStyleType {

    @XmlEnumValue("Plain")
    PLAIN("Plain"),
    @XmlEnumValue("Bold")
    BOLD("Bold"),
    @XmlEnumValue("Italic")
    ITALIC("Italic"),
    @XmlEnumValue("Bold Italic")
    BOLD_ITALIC("Bold Italic");
    private final String value;

    FontStyleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FontStyleType fromValue(String v) {
        for (FontStyleType c: FontStyleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
