//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.20 at 04:07:50 PM CST 
//


package org.shaolin.bmdp.datamodel.page;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FunctionReconfigurationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FunctionReconfigurationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bmdp.shaolin.org/datamodel/Page}ReconfigurationType">
 *       &lt;attribute name="originFunctionName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="overrideFunctionName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FunctionReconfigurationType")
public class FunctionReconfigurationType
    extends ReconfigurationType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "originFunctionName", required = true)
    protected String originFunctionName;
    @XmlAttribute(name = "overrideFunctionName", required = true)
    protected String overrideFunctionName;

    /**
     * Gets the value of the originFunctionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginFunctionName() {
        return originFunctionName;
    }

    /**
     * Sets the value of the originFunctionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginFunctionName(String value) {
        this.originFunctionName = value;
    }

    /**
     * Gets the value of the overrideFunctionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOverrideFunctionName() {
        return overrideFunctionName;
    }

    /**
     * Sets the value of the overrideFunctionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOverrideFunctionName(String value) {
        this.overrideFunctionName = value;
    }

}
