//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.17 at 10:54:36 PM CST 
//


package org.shaolin.bmdp.datamodel.page;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.shaolin.bmdp.datamodel.common.ExpressionType;
import org.shaolin.bmdp.datamodel.common.NameExpressionType;


/**
 * <p>Java class for OpInvokeWorkflowType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OpInvokeWorkflowType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bmdp.shaolin.org/datamodel/Page}OpType">
 *       &lt;sequence>
 *         &lt;element name="condition" type="{http://bmdp.shaolin.org/datamodel/Common}ExpressionType"/>
 *         &lt;element name="outDataMapping" type="{http://bmdp.shaolin.org/datamodel/Common}NameExpressionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="eventProducer" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OpInvokeWorkflowType", propOrder = {
    "condition",
    "outDataMappings"
})
public class OpInvokeWorkflowType
    extends OpType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected ExpressionType condition;
    @XmlElement(name = "outDataMapping")
    protected List<NameExpressionType> outDataMappings;
    @XmlAttribute(name = "eventProducer", required = true)
    protected String eventProducer;

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link ExpressionType }
     *     
     */
    public ExpressionType getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpressionType }
     *     
     */
    public void setCondition(ExpressionType value) {
        this.condition = value;
    }

    /**
     * Gets the value of the outDataMappings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outDataMappings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutDataMappings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameExpressionType }
     * 
     * 
     */
    public List<NameExpressionType> getOutDataMappings() {
        if (outDataMappings == null) {
            outDataMappings = new ArrayList<NameExpressionType>();
        }
        return this.outDataMappings;
    }

    /**
     * Gets the value of the eventProducer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventProducer() {
        return eventProducer;
    }

    /**
     * Sets the value of the eventProducer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventProducer(String value) {
        this.eventProducer = value;
    }

}
