//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.20 at 04:07:50 PM CST 
//


package org.shaolin.bmdp.datamodel.page;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.shaolin.bmdp.datamodel.common.TargetEntityType;


/**
 * <p>Java class for SimpleComponentMappingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimpleComponentMappingType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bmdp.shaolin.org/datamodel/Page}ComponentMappingType">
 *       &lt;sequence>
 *         &lt;element name="mappingRule" type="{http://bmdp.shaolin.org/datamodel/Common}TargetEntityType"/>
 *         &lt;element name="UIComponent" type="{http://bmdp.shaolin.org/datamodel/Page}UIComponentParamType" maxOccurs="unbounded"/>
 *         &lt;element name="DataComponent" type="{http://bmdp.shaolin.org/datamodel/Page}DataParamType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimpleComponentMappingType", propOrder = {
    "mappingRule",
    "uiComponents",
    "dataComponents"
})
public class SimpleComponentMappingType
    extends ComponentMappingType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected TargetEntityType mappingRule;
    @XmlElement(name = "UIComponent", required = true)
    protected List<UIComponentParamType> uiComponents;
    @XmlElement(name = "DataComponent", required = true)
    protected List<DataParamType> dataComponents;

    /**
     * Gets the value of the mappingRule property.
     * 
     * @return
     *     possible object is
     *     {@link TargetEntityType }
     *     
     */
    public TargetEntityType getMappingRule() {
        return mappingRule;
    }

    /**
     * Sets the value of the mappingRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetEntityType }
     *     
     */
    public void setMappingRule(TargetEntityType value) {
        this.mappingRule = value;
    }

    /**
     * Gets the value of the uiComponents property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the uiComponents property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUIComponents().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UIComponentParamType }
     * 
     * 
     */
    public List<UIComponentParamType> getUIComponents() {
        if (uiComponents == null) {
            uiComponents = new ArrayList<UIComponentParamType>();
        }
        return this.uiComponents;
    }

    /**
     * Gets the value of the dataComponents property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataComponents property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataComponents().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataParamType }
     * 
     * 
     */
    public List<DataParamType> getDataComponents() {
        if (dataComponents == null) {
            dataComponents = new ArrayList<DataParamType>();
        }
        return this.dataComponents;
    }

}
