//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.20 at 04:07:50 PM CST 
//


package org.shaolin.bmdp.datamodel.page;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.shaolin.bmdp.datamodel.common.EntityType;
import org.shaolin.bmdp.datamodel.common.VariableType;


/**
 * <p>Java class for UIBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UIBaseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bmdp.shaolin.org/datamodel/Common}EntityType">
 *       &lt;sequence>
 *         &lt;element name="eventHandler" type="{http://bmdp.shaolin.org/datamodel/Page}FunctionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="variable" type="{http://bmdp.shaolin.org/datamodel/Common}VariableType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="reconfigurableProperty" type="{http://bmdp.shaolin.org/datamodel/Page}ReconfigurableType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UIBaseType", propOrder = {
    "eventHandlers",
    "variables",
    "reconfigurableProperties"
})
@XmlSeeAlso({
    UIEntity.class
})
public abstract class UIBaseType
    extends EntityType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "eventHandler")
    protected List<FunctionType> eventHandlers;
    @XmlElement(name = "variable")
    protected List<VariableType> variables;
    @XmlElement(name = "reconfigurableProperty")
    protected List<ReconfigurableType> reconfigurableProperties;

    /**
     * Gets the value of the eventHandlers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventHandlers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventHandlers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FunctionType }
     * 
     * 
     */
    public List<FunctionType> getEventHandlers() {
        if (eventHandlers == null) {
            eventHandlers = new ArrayList<FunctionType>();
        }
        return this.eventHandlers;
    }

    /**
     * Gets the value of the variables property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the variables property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVariables().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VariableType }
     * 
     * 
     */
    public List<VariableType> getVariables() {
        if (variables == null) {
            variables = new ArrayList<VariableType>();
        }
        return this.variables;
    }

    /**
     * Gets the value of the reconfigurableProperties property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reconfigurableProperties property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReconfigurableProperties().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReconfigurableType }
     * 
     * 
     */
    public List<ReconfigurableType> getReconfigurableProperties() {
        if (reconfigurableProperties == null) {
            reconfigurableProperties = new ArrayList<ReconfigurableType>();
        }
        return this.reconfigurableProperties;
    }

}
