//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.22 at 12:07:44 AM CST 
//


package org.shaolin.bmdp.datamodel.page;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UIChartType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UIChartType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bmdp.shaolin.org/datamodel/Page}UIComponentType">
 *       &lt;sequence>
 *         &lt;element name="beElement" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="strokeColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="column" type="{http://bmdp.shaolin.org/datamodel/Page}UITableColumnType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UIChartType", propOrder = {
    "beElement",
    "color",
    "strokeColor",
    "columns"
})
@XmlSeeAlso({
    UIBarChartType.class,
    UIPieChartType.class,
    UIRadarChartType.class,
    UIPolarChartType.class,
    UILinearChartType.class
})
public class UIChartType
    extends UIComponentType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String beElement;
    @XmlElement(required = true, defaultValue = "rgba(151,187,205,0.2)")
    protected String color;
    @XmlElement(required = true, defaultValue = "#fff")
    protected String strokeColor;
    @XmlElement(name = "column", required = true)
    protected List<UITableColumnType> columns;

    /**
     * Gets the value of the beElement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeElement() {
        return beElement;
    }

    /**
     * Sets the value of the beElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeElement(String value) {
        this.beElement = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the strokeColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrokeColor() {
        return strokeColor;
    }

    /**
     * Sets the value of the strokeColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrokeColor(String value) {
        this.strokeColor = value;
    }

    /**
     * Gets the value of the columns property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the columns property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getColumns().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UITableColumnType }
     * 
     * 
     */
    public List<UITableColumnType> getColumns() {
        if (columns == null) {
            columns = new ArrayList<UITableColumnType>();
        }
        return this.columns;
    }

}
