//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.15 at 07:46:28 PM CST 
//


package org.shaolin.bmdp.datamodel.page;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * in principle, UIComponent should be abstract, if a user uses this type, it means this component is used for component reconfiguration
 * 
 * <p>Java class for UIComponentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UIComponentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Property" type="{http://bmdp.shaolin.org/datamodel/Page}PropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EventListener" type="{http://bmdp.shaolin.org/datamodel/Page}EventListenerType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="secure" type="{http://bmdp.shaolin.org/datamodel/Page}BooleanPropertyType" minOccurs="0"/>
 *         &lt;element name="visible" type="{http://bmdp.shaolin.org/datamodel/Page}PropertyValueType" minOccurs="0"/>
 *         &lt;element name="readOnly" type="{http://bmdp.shaolin.org/datamodel/Page}PropertyValueType" minOccurs="0"/>
 *         &lt;element name="editable" type="{http://bmdp.shaolin.org/datamodel/Page}PropertyValueType" minOccurs="0"/>
 *         &lt;element name="UIStyle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="preIncludePage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="postIncludePage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UISkin" type="{http://bmdp.shaolin.org/datamodel/Page}UISkinType" minOccurs="0"/>
 *         &lt;element name="widgetLabel" type="{http://bmdp.shaolin.org/datamodel/Page}PropertyValueType" minOccurs="0"/>
 *         &lt;element name="widgetLabelColor" type="{http://bmdp.shaolin.org/datamodel/Page}PropertyValueType" minOccurs="0"/>
 *         &lt;element name="widgetLabelFont" type="{http://bmdp.shaolin.org/datamodel/Page}PropertyValueType" minOccurs="0"/>
 *         &lt;element name="initValidation" type="{http://bmdp.shaolin.org/datamodel/Page}PropertyValueType" minOccurs="0"/>
 *         &lt;element name="validator" type="{http://bmdp.shaolin.org/datamodel/Page}PropertyValueType" minOccurs="0"/>
 *         &lt;element name="viewPermission" type="{http://bmdp.shaolin.org/datamodel/Page}PropertyValueType" minOccurs="0"/>
 *         &lt;element name="editPermission" type="{http://bmdp.shaolin.org/datamodel/Page}PropertyValueType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="UIID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UIComponentType", propOrder = {
    "properties",
    "eventListeners",
    "secure",
    "visible",
    "readOnly",
    "editable",
    "uiStyle",
    "preIncludePage",
    "postIncludePage",
    "uiSkin",
    "widgetLabel",
    "widgetLabelColor",
    "widgetLabelFont",
    "initValidation",
    "validator",
    "viewPermission",
    "editPermission"
})
@XmlSeeAlso({
    UIFrameType.class,
    UIWebTreeType.class,
    UIReferenceEntityType.class,
    UIContainerType.class,
    UIWebMenuType.class,
    UIImageType.class,
    UITabPaneType.class,
    UISelectComponentType.class,
    UIEmptyType.class,
    UIFileType.class,
    UITableType.class,
    UIFlowDiagramType.class,
    UIChoiceType.class,
    UITextComponentType.class
})
public abstract class UIComponentType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Property")
    protected List<PropertyType> properties;
    @XmlElement(name = "EventListener")
    protected List<EventListenerType> eventListeners;
    protected BooleanPropertyType secure;
    protected PropertyValueType visible;
    protected PropertyValueType readOnly;
    protected PropertyValueType editable;
    @XmlElement(name = "UIStyle")
    protected String uiStyle;
    protected String preIncludePage;
    protected String postIncludePage;
    @XmlElement(name = "UISkin")
    protected UISkinType uiSkin;
    protected PropertyValueType widgetLabel;
    protected PropertyValueType widgetLabelColor;
    protected PropertyValueType widgetLabelFont;
    protected PropertyValueType initValidation;
    protected PropertyValueType validator;
    protected PropertyValueType viewPermission;
    protected PropertyValueType editPermission;
    @XmlAttribute(name = "UIID", required = true)
    protected String uiid;

    /**
     * Gets the value of the properties property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the properties property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperties().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertyType }
     * 
     * 
     */
    public List<PropertyType> getProperties() {
        if (properties == null) {
            properties = new ArrayList<PropertyType>();
        }
        return this.properties;
    }

    /**
     * Gets the value of the eventListeners property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventListeners property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventListeners().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventListenerType }
     * 
     * 
     */
    public List<EventListenerType> getEventListeners() {
        if (eventListeners == null) {
            eventListeners = new ArrayList<EventListenerType>();
        }
        return this.eventListeners;
    }

    /**
     * Gets the value of the secure property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanPropertyType }
     *     
     */
    public BooleanPropertyType getSecure() {
        return secure;
    }

    /**
     * Sets the value of the secure property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanPropertyType }
     *     
     */
    public void setSecure(BooleanPropertyType value) {
        this.secure = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyValueType }
     *     
     */
    public PropertyValueType getVisible() {
        return visible;
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyValueType }
     *     
     */
    public void setVisible(PropertyValueType value) {
        this.visible = value;
    }

    /**
     * Gets the value of the readOnly property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyValueType }
     *     
     */
    public PropertyValueType getReadOnly() {
        return readOnly;
    }

    /**
     * Sets the value of the readOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyValueType }
     *     
     */
    public void setReadOnly(PropertyValueType value) {
        this.readOnly = value;
    }

    /**
     * Gets the value of the editable property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyValueType }
     *     
     */
    public PropertyValueType getEditable() {
        return editable;
    }

    /**
     * Sets the value of the editable property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyValueType }
     *     
     */
    public void setEditable(PropertyValueType value) {
        this.editable = value;
    }

    /**
     * Gets the value of the uiStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUIStyle() {
        return uiStyle;
    }

    /**
     * Sets the value of the uiStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUIStyle(String value) {
        this.uiStyle = value;
    }

    /**
     * Gets the value of the preIncludePage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreIncludePage() {
        return preIncludePage;
    }

    /**
     * Sets the value of the preIncludePage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreIncludePage(String value) {
        this.preIncludePage = value;
    }

    /**
     * Gets the value of the postIncludePage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostIncludePage() {
        return postIncludePage;
    }

    /**
     * Sets the value of the postIncludePage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostIncludePage(String value) {
        this.postIncludePage = value;
    }

    /**
     * Gets the value of the uiSkin property.
     * 
     * @return
     *     possible object is
     *     {@link UISkinType }
     *     
     */
    public UISkinType getUISkin() {
        return uiSkin;
    }

    /**
     * Sets the value of the uiSkin property.
     * 
     * @param value
     *     allowed object is
     *     {@link UISkinType }
     *     
     */
    public void setUISkin(UISkinType value) {
        this.uiSkin = value;
    }

    /**
     * Gets the value of the widgetLabel property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyValueType }
     *     
     */
    public PropertyValueType getWidgetLabel() {
        return widgetLabel;
    }

    /**
     * Sets the value of the widgetLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyValueType }
     *     
     */
    public void setWidgetLabel(PropertyValueType value) {
        this.widgetLabel = value;
    }

    /**
     * Gets the value of the widgetLabelColor property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyValueType }
     *     
     */
    public PropertyValueType getWidgetLabelColor() {
        return widgetLabelColor;
    }

    /**
     * Sets the value of the widgetLabelColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyValueType }
     *     
     */
    public void setWidgetLabelColor(PropertyValueType value) {
        this.widgetLabelColor = value;
    }

    /**
     * Gets the value of the widgetLabelFont property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyValueType }
     *     
     */
    public PropertyValueType getWidgetLabelFont() {
        return widgetLabelFont;
    }

    /**
     * Sets the value of the widgetLabelFont property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyValueType }
     *     
     */
    public void setWidgetLabelFont(PropertyValueType value) {
        this.widgetLabelFont = value;
    }

    /**
     * Gets the value of the initValidation property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyValueType }
     *     
     */
    public PropertyValueType getInitValidation() {
        return initValidation;
    }

    /**
     * Sets the value of the initValidation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyValueType }
     *     
     */
    public void setInitValidation(PropertyValueType value) {
        this.initValidation = value;
    }

    /**
     * Gets the value of the validator property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyValueType }
     *     
     */
    public PropertyValueType getValidator() {
        return validator;
    }

    /**
     * Sets the value of the validator property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyValueType }
     *     
     */
    public void setValidator(PropertyValueType value) {
        this.validator = value;
    }

    /**
     * Gets the value of the viewPermission property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyValueType }
     *     
     */
    public PropertyValueType getViewPermission() {
        return viewPermission;
    }

    /**
     * Sets the value of the viewPermission property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyValueType }
     *     
     */
    public void setViewPermission(PropertyValueType value) {
        this.viewPermission = value;
    }

    /**
     * Gets the value of the editPermission property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyValueType }
     *     
     */
    public PropertyValueType getEditPermission() {
        return editPermission;
    }

    /**
     * Sets the value of the editPermission property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyValueType }
     *     
     */
    public void setEditPermission(PropertyValueType value) {
        this.editPermission = value;
    }

    /**
     * Gets the value of the uiid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUIID() {
        return uiid;
    }

    /**
     * Sets the value of the uiid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUIID(String value) {
        this.uiid = value;
    }

}
