//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.15 at 04:56:22 PM CST 
//


package org.shaolin.bmdp.datamodel.page;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * container type should have a layout, a  list of components, a list of component layout constraints and a list of handlers
 * 
 * <p>Java class for UIContainerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UIContainerType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bmdp.shaolin.org/datamodel/Page}UIComponentType">
 *       &lt;sequence>
 *         &lt;element name="layout" type="{http://bmdp.shaolin.org/datamodel/Page}UILayoutType" minOccurs="0"/>
 *         &lt;element name="dynamicUIFilter" type="{http://bmdp.shaolin.org/datamodel/Page}PropertyValueType" minOccurs="0"/>
 *         &lt;element name="component" type="{http://bmdp.shaolin.org/datamodel/Page}UIComponentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="layoutConstraint" type="{http://bmdp.shaolin.org/datamodel/Page}ComponentConstraintType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="validationList" type="{http://bmdp.shaolin.org/datamodel/Page}PropertyValueType" minOccurs="0"/>
 *         &lt;element name="constructorCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="dynamicUI" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UIContainerType", propOrder = {
    "layout",
    "dynamicUIFilter",
    "components",
    "layoutConstraints",
    "validationList",
    "constructorCode"
})
@XmlSeeAlso({
    UIPanelType.class
})
public abstract class UIContainerType
    extends UIComponentType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected UILayoutType layout;
    protected PropertyValueType dynamicUIFilter;
    @XmlElement(name = "component")
    protected List<UIComponentType> components;
    @XmlElement(name = "layoutConstraint")
    protected List<ComponentConstraintType> layoutConstraints;
    protected PropertyValueType validationList;
    protected String constructorCode;
    @XmlAttribute(name = "dynamicUI")
    protected Boolean dynamicUI;

    /**
     * Gets the value of the layout property.
     * 
     * @return
     *     possible object is
     *     {@link UILayoutType }
     *     
     */
    public UILayoutType getLayout() {
        return layout;
    }

    /**
     * Sets the value of the layout property.
     * 
     * @param value
     *     allowed object is
     *     {@link UILayoutType }
     *     
     */
    public void setLayout(UILayoutType value) {
        this.layout = value;
    }

    /**
     * Gets the value of the dynamicUIFilter property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyValueType }
     *     
     */
    public PropertyValueType getDynamicUIFilter() {
        return dynamicUIFilter;
    }

    /**
     * Sets the value of the dynamicUIFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyValueType }
     *     
     */
    public void setDynamicUIFilter(PropertyValueType value) {
        this.dynamicUIFilter = value;
    }

    /**
     * Gets the value of the components property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the components property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComponents().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UIComponentType }
     * 
     * 
     */
    public List<UIComponentType> getComponents() {
        if (components == null) {
            components = new ArrayList<UIComponentType>();
        }
        return this.components;
    }

    /**
     * Gets the value of the layoutConstraints property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the layoutConstraints property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLayoutConstraints().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComponentConstraintType }
     * 
     * 
     */
    public List<ComponentConstraintType> getLayoutConstraints() {
        if (layoutConstraints == null) {
            layoutConstraints = new ArrayList<ComponentConstraintType>();
        }
        return this.layoutConstraints;
    }

    /**
     * Gets the value of the validationList property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyValueType }
     *     
     */
    public PropertyValueType getValidationList() {
        return validationList;
    }

    /**
     * Sets the value of the validationList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyValueType }
     *     
     */
    public void setValidationList(PropertyValueType value) {
        this.validationList = value;
    }

    /**
     * Gets the value of the constructorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConstructorCode() {
        return constructorCode;
    }

    /**
     * Sets the value of the constructorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConstructorCode(String value) {
        this.constructorCode = value;
    }

    /**
     * Gets the value of the dynamicUI property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDynamicUI() {
        return dynamicUI;
    }

    /**
     * Sets the value of the dynamicUI property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDynamicUI(Boolean value) {
        this.dynamicUI = value;
    }

}
