//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.27 at 04:32:49 PM CST 
//


package org.shaolin.bmdp.datamodel.page;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UIFlowDiagramType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UIFlowDiagramType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bmdp.shaolin.org/datamodel/Page}UIComponentType">
 *       &lt;sequence>
 *         &lt;element name="openToolBar" type="{http://bmdp.shaolin.org/datamodel/Page}BooleanPropertyType"/>
 *         &lt;element name="loadDateModel" type="{http://bmdp.shaolin.org/datamodel/Page}ExpressionPropertyType"/>
 *         &lt;element name="loadFlow" type="{http://bmdp.shaolin.org/datamodel/Page}ExpressionPropertyType"/>
 *         &lt;element name="defaultActions" type="{http://bmdp.shaolin.org/datamodel/Page}UIFlowDefaultActionType"/>
 *         &lt;element name="actionGroup" type="{http://bmdp.shaolin.org/datamodel/Page}UITableActionGroupType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="flowName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UIFlowDiagramType", propOrder = {
    "openToolBar",
    "loadDateModel",
    "loadFlow",
    "defaultActions",
    "actionGroups"
})
public class UIFlowDiagramType
    extends UIComponentType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected BooleanPropertyType openToolBar;
    @XmlElement(required = true)
    protected ExpressionPropertyType loadDateModel;
    @XmlElement(required = true)
    protected ExpressionPropertyType loadFlow;
    @XmlElement(required = true)
    protected UIFlowDefaultActionType defaultActions;
    @XmlElement(name = "actionGroup")
    protected List<UITableActionGroupType> actionGroups;
    @XmlAttribute(name = "flowName")
    protected String flowName;

    /**
     * Gets the value of the openToolBar property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanPropertyType }
     *     
     */
    public BooleanPropertyType getOpenToolBar() {
        return openToolBar;
    }

    /**
     * Sets the value of the openToolBar property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanPropertyType }
     *     
     */
    public void setOpenToolBar(BooleanPropertyType value) {
        this.openToolBar = value;
    }

    /**
     * Gets the value of the loadDateModel property.
     * 
     * @return
     *     possible object is
     *     {@link ExpressionPropertyType }
     *     
     */
    public ExpressionPropertyType getLoadDateModel() {
        return loadDateModel;
    }

    /**
     * Sets the value of the loadDateModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpressionPropertyType }
     *     
     */
    public void setLoadDateModel(ExpressionPropertyType value) {
        this.loadDateModel = value;
    }

    /**
     * Gets the value of the loadFlow property.
     * 
     * @return
     *     possible object is
     *     {@link ExpressionPropertyType }
     *     
     */
    public ExpressionPropertyType getLoadFlow() {
        return loadFlow;
    }

    /**
     * Sets the value of the loadFlow property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpressionPropertyType }
     *     
     */
    public void setLoadFlow(ExpressionPropertyType value) {
        this.loadFlow = value;
    }

    /**
     * Gets the value of the defaultActions property.
     * 
     * @return
     *     possible object is
     *     {@link UIFlowDefaultActionType }
     *     
     */
    public UIFlowDefaultActionType getDefaultActions() {
        return defaultActions;
    }

    /**
     * Sets the value of the defaultActions property.
     * 
     * @param value
     *     allowed object is
     *     {@link UIFlowDefaultActionType }
     *     
     */
    public void setDefaultActions(UIFlowDefaultActionType value) {
        this.defaultActions = value;
    }

    /**
     * Gets the value of the actionGroups property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the actionGroups property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActionGroups().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UITableActionGroupType }
     * 
     * 
     */
    public List<UITableActionGroupType> getActionGroups() {
        if (actionGroups == null) {
            actionGroups = new ArrayList<UITableActionGroupType>();
        }
        return this.actionGroups;
    }

    /**
     * Gets the value of the flowName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlowName() {
        return flowName;
    }

    /**
     * Sets the value of the flowName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlowName(String value) {
        this.flowName = value;
    }

}
