//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.27 at 04:32:49 PM CST 
//


package org.shaolin.bmdp.datamodel.page;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UIFlowDefaultActionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UIFlowDefaultActionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="newNode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="openNode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="deleteNode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="refreshFlow" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="saveFlow" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UIFlowDefaultActionType", propOrder = {
    "newNode",
    "openNode",
    "deleteNode",
    "refreshFlow",
    "saveFlow"
})
public class UIFlowDefaultActionType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String newNode;
    @XmlElement(required = true)
    protected String openNode;
    @XmlElement(required = true)
    protected String deleteNode;
    @XmlElement(required = true)
    protected String refreshFlow;
    @XmlElement(required = true)
    protected String saveFlow;

    /**
     * Gets the value of the newNode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewNode() {
        return newNode;
    }

    /**
     * Sets the value of the newNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewNode(String value) {
        this.newNode = value;
    }

    /**
     * Gets the value of the openNode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpenNode() {
        return openNode;
    }

    /**
     * Sets the value of the openNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpenNode(String value) {
        this.openNode = value;
    }

    /**
     * Gets the value of the deleteNode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeleteNode() {
        return deleteNode;
    }

    /**
     * Sets the value of the deleteNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeleteNode(String value) {
        this.deleteNode = value;
    }

    /**
     * Gets the value of the refreshFlow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefreshFlow() {
        return refreshFlow;
    }

    /**
     * Sets the value of the refreshFlow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefreshFlow(String value) {
        this.refreshFlow = value;
    }

    /**
     * Gets the value of the saveFlow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSaveFlow() {
        return saveFlow;
    }

    /**
     * Sets the value of the saveFlow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSaveFlow(String value) {
        this.saveFlow = value;
    }

}
