//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.11 at 11:17:42 PM CST 
//


package org.shaolin.bmdp.datamodel.page;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UIImageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UIImageType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bmdp.shaolin.org/datamodel/Page}UIComponentType">
 *       &lt;sequence>
 *         &lt;element name="src" type="{http://bmdp.shaolin.org/datamodel/Page}PropertyValueType"/>
 *         &lt;element name="isGallery" type="{http://bmdp.shaolin.org/datamodel/Page}BooleanPropertyType"/>
 *         &lt;element name="showWords" type="{http://bmdp.shaolin.org/datamodel/Page}BooleanPropertyType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UIImageType", propOrder = {
    "src",
    "isGallery",
    "showWords"
})
public class UIImageType
    extends UIComponentType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected PropertyValueType src;
    @XmlElement(required = true)
    protected BooleanPropertyType isGallery;
    @XmlElement(required = true)
    protected BooleanPropertyType showWords;

    /**
     * Gets the value of the src property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyValueType }
     *     
     */
    public PropertyValueType getSrc() {
        return src;
    }

    /**
     * Sets the value of the src property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyValueType }
     *     
     */
    public void setSrc(PropertyValueType value) {
        this.src = value;
    }

    /**
     * Gets the value of the isGallery property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanPropertyType }
     *     
     */
    public BooleanPropertyType getIsGallery() {
        return isGallery;
    }

    /**
     * Sets the value of the isGallery property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanPropertyType }
     *     
     */
    public void setIsGallery(BooleanPropertyType value) {
        this.isGallery = value;
    }

    /**
     * Gets the value of the showWords property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanPropertyType }
     *     
     */
    public BooleanPropertyType getShowWords() {
        return showWords;
    }

    /**
     * Sets the value of the showWords property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanPropertyType }
     *     
     */
    public void setShowWords(BooleanPropertyType value) {
        this.showWords = value;
    }

}
