//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.20 at 04:07:50 PM CST 
//


package org.shaolin.bmdp.datamodel.page;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UIListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UIListType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bmdp.shaolin.org/datamodel/Page}UIMultiChoiceType">
 *       &lt;sequence>
 *         &lt;element name="allowBlank" type="{http://bmdp.shaolin.org/datamodel/Page}PropertyValueType" minOccurs="0"/>
 *         &lt;element name="allowBlankText" type="{http://bmdp.shaolin.org/datamodel/Page}PropertyValueType" minOccurs="0"/>
 *         &lt;element name="size" type="{http://bmdp.shaolin.org/datamodel/Page}PropertyValueType" minOccurs="0"/>
 *         &lt;element name="multiple" type="{http://bmdp.shaolin.org/datamodel/Page}PropertyValueType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UIListType", propOrder = {
    "allowBlank",
    "allowBlankText",
    "size",
    "multiple"
})
public class UIListType
    extends UIMultiChoiceType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected PropertyValueType allowBlank;
    protected PropertyValueType allowBlankText;
    protected PropertyValueType size;
    protected PropertyValueType multiple;

    /**
     * Gets the value of the allowBlank property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyValueType }
     *     
     */
    public PropertyValueType getAllowBlank() {
        return allowBlank;
    }

    /**
     * Sets the value of the allowBlank property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyValueType }
     *     
     */
    public void setAllowBlank(PropertyValueType value) {
        this.allowBlank = value;
    }

    /**
     * Gets the value of the allowBlankText property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyValueType }
     *     
     */
    public PropertyValueType getAllowBlankText() {
        return allowBlankText;
    }

    /**
     * Sets the value of the allowBlankText property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyValueType }
     *     
     */
    public void setAllowBlankText(PropertyValueType value) {
        this.allowBlankText = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyValueType }
     *     
     */
    public PropertyValueType getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyValueType }
     *     
     */
    public void setSize(PropertyValueType value) {
        this.size = value;
    }

    /**
     * Gets the value of the multiple property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyValueType }
     *     
     */
    public PropertyValueType getMultiple() {
        return multiple;
    }

    /**
     * Sets the value of the multiple property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyValueType }
     *     
     */
    public void setMultiple(PropertyValueType value) {
        this.multiple = value;
    }

}
