//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.20 at 04:07:50 PM CST 
//


package org.shaolin.bmdp.datamodel.page;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UIMultiChoiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UIMultiChoiceType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bmdp.shaolin.org/datamodel/Page}UIChoiceType">
 *       &lt;sequence>
 *         &lt;element name="selectedValuesConstraint" type="{http://bmdp.shaolin.org/datamodel/Page}PropertyValueType" minOccurs="0"/>
 *         &lt;element name="selectedValuesConstraintText" type="{http://bmdp.shaolin.org/datamodel/Page}PropertyValueType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UIMultiChoiceType", propOrder = {
    "selectedValuesConstraint",
    "selectedValuesConstraintText"
})
@XmlSeeAlso({
    UIListType.class,
    UICheckBoxGroupType.class
})
public class UIMultiChoiceType
    extends UIChoiceType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected PropertyValueType selectedValuesConstraint;
    protected PropertyValueType selectedValuesConstraintText;

    /**
     * Gets the value of the selectedValuesConstraint property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyValueType }
     *     
     */
    public PropertyValueType getSelectedValuesConstraint() {
        return selectedValuesConstraint;
    }

    /**
     * Sets the value of the selectedValuesConstraint property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyValueType }
     *     
     */
    public void setSelectedValuesConstraint(PropertyValueType value) {
        this.selectedValuesConstraint = value;
    }

    /**
     * Gets the value of the selectedValuesConstraintText property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyValueType }
     *     
     */
    public PropertyValueType getSelectedValuesConstraintText() {
        return selectedValuesConstraintText;
    }

    /**
     * Sets the value of the selectedValuesConstraintText property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyValueType }
     *     
     */
    public void setSelectedValuesConstraintText(PropertyValueType value) {
        this.selectedValuesConstraintText = value;
    }

}
