//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.20 at 04:07:50 PM CST 
//


package org.shaolin.bmdp.datamodel.page;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.shaolin.bmdp.datamodel.common.TargetEntityType;


/**
 * the reference entity could be either normal entity reference or template reference, in template reference, user should specify the abstract component reconfiguration
 * 
 * <p>Java class for UIReferenceEntityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UIReferenceEntityType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bmdp.shaolin.org/datamodel/Page}UIComponentType">
 *       &lt;sequence>
 *         &lt;element name="referenceEntity" type="{http://bmdp.shaolin.org/datamodel/Common}TargetEntityType"/>
 *         &lt;element name="reconfiguration" type="{http://bmdp.shaolin.org/datamodel/Page}ReconfigurationType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isReferenceInterface" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UIReferenceEntityType", propOrder = {
    "referenceEntity",
    "reconfigurations"
})
public class UIReferenceEntityType
    extends UIComponentType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected TargetEntityType referenceEntity;
    @XmlElement(name = "reconfiguration")
    protected List<ReconfigurationType> reconfigurations;
    @XmlAttribute(name = "isReferenceInterface")
    protected Boolean isReferenceInterface;

    /**
     * Gets the value of the referenceEntity property.
     * 
     * @return
     *     possible object is
     *     {@link TargetEntityType }
     *     
     */
    public TargetEntityType getReferenceEntity() {
        return referenceEntity;
    }

    /**
     * Sets the value of the referenceEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetEntityType }
     *     
     */
    public void setReferenceEntity(TargetEntityType value) {
        this.referenceEntity = value;
    }

    /**
     * Gets the value of the reconfigurations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reconfigurations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReconfigurations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReconfigurationType }
     * 
     * 
     */
    public List<ReconfigurationType> getReconfigurations() {
        if (reconfigurations == null) {
            reconfigurations = new ArrayList<ReconfigurationType>();
        }
        return this.reconfigurations;
    }

    /**
     * Gets the value of the isReferenceInterface property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsReferenceInterface() {
        if (isReferenceInterface == null) {
            return false;
        } else {
            return isReferenceInterface;
        }
    }

    /**
     * Sets the value of the isReferenceInterface property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsReferenceInterface(Boolean value) {
        this.isReferenceInterface = value;
    }

}
