//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.20 at 04:07:50 PM CST 
//


package org.shaolin.bmdp.datamodel.page;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UISingleChoiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UISingleChoiceType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bmdp.shaolin.org/datamodel/Page}UIChoiceType">
 *       &lt;sequence>
 *         &lt;element name="selectedValueConstraint" type="{http://bmdp.shaolin.org/datamodel/Page}PropertyValueType" minOccurs="0"/>
 *         &lt;element name="selectedValueConstraintText" type="{http://bmdp.shaolin.org/datamodel/Page}PropertyValueType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UISingleChoiceType", propOrder = {
    "selectedValueConstraint",
    "selectedValueConstraintText"
})
@XmlSeeAlso({
    UIComboBoxType.class,
    UIRadioButtonGroupType.class
})
public abstract class UISingleChoiceType
    extends UIChoiceType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected PropertyValueType selectedValueConstraint;
    protected PropertyValueType selectedValueConstraintText;

    /**
     * Gets the value of the selectedValueConstraint property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyValueType }
     *     
     */
    public PropertyValueType getSelectedValueConstraint() {
        return selectedValueConstraint;
    }

    /**
     * Sets the value of the selectedValueConstraint property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyValueType }
     *     
     */
    public void setSelectedValueConstraint(PropertyValueType value) {
        this.selectedValueConstraint = value;
    }

    /**
     * Gets the value of the selectedValueConstraintText property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyValueType }
     *     
     */
    public PropertyValueType getSelectedValueConstraintText() {
        return selectedValueConstraintText;
    }

    /**
     * Sets the value of the selectedValueConstraintText property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyValueType }
     *     
     */
    public void setSelectedValueConstraintText(PropertyValueType value) {
        this.selectedValueConstraintText = value;
    }

}
