//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.28 at 02:29:54 PM CST 
//


package org.shaolin.bmdp.datamodel.page;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UITabPaneItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UITabPaneItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://bmdp.shaolin.org/datamodel/Page}PropertyValueType"/>
 *         &lt;element name="refEntity" type="{http://bmdp.shaolin.org/datamodel/Page}UIReferenceEntityType"/>
 *         &lt;element name="frame" type="{http://bmdp.shaolin.org/datamodel/Page}UIFrameType"/>
 *         &lt;element name="panel" type="{http://bmdp.shaolin.org/datamodel/Page}UIPanelType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="uiid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UITabPaneItemType", propOrder = {
    "title",
    "refEntity",
    "frame",
    "panel"
})
public class UITabPaneItemType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected PropertyValueType title;
    @XmlElement(required = true)
    protected UIReferenceEntityType refEntity;
    @XmlElement(required = true)
    protected UIFrameType frame;
    @XmlElement(required = true)
    protected UIPanelType panel;
    @XmlAttribute(name = "uiid")
    protected String uiid;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyValueType }
     *     
     */
    public PropertyValueType getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyValueType }
     *     
     */
    public void setTitle(PropertyValueType value) {
        this.title = value;
    }

    /**
     * Gets the value of the refEntity property.
     * 
     * @return
     *     possible object is
     *     {@link UIReferenceEntityType }
     *     
     */
    public UIReferenceEntityType getRefEntity() {
        return refEntity;
    }

    /**
     * Sets the value of the refEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link UIReferenceEntityType }
     *     
     */
    public void setRefEntity(UIReferenceEntityType value) {
        this.refEntity = value;
    }

    /**
     * Gets the value of the frame property.
     * 
     * @return
     *     possible object is
     *     {@link UIFrameType }
     *     
     */
    public UIFrameType getFrame() {
        return frame;
    }

    /**
     * Sets the value of the frame property.
     * 
     * @param value
     *     allowed object is
     *     {@link UIFrameType }
     *     
     */
    public void setFrame(UIFrameType value) {
        this.frame = value;
    }

    /**
     * Gets the value of the panel property.
     * 
     * @return
     *     possible object is
     *     {@link UIPanelType }
     *     
     */
    public UIPanelType getPanel() {
        return panel;
    }

    /**
     * Sets the value of the panel property.
     * 
     * @param value
     *     allowed object is
     *     {@link UIPanelType }
     *     
     */
    public void setPanel(UIPanelType value) {
        this.panel = value;
    }

    /**
     * Gets the value of the uiid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUiid() {
        return uiid;
    }

    /**
     * Sets the value of the uiid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUiid(String value) {
        this.uiid = value;
    }

}
