//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.15 at 07:28:27 PM CST 
//


package org.shaolin.bmdp.datamodel.page;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UITableDefaultActionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UITableDefaultActionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="defaultNewAction" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="defaultOpenAction" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="defaultEnableAction" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="defaultDisableAction" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="defaultDeleteAction" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UITableDefaultActionType", propOrder = {
    "defaultNewAction",
    "defaultOpenAction",
    "defaultEnableAction",
    "defaultDisableAction",
    "defaultDeleteAction"
})
public class UITableDefaultActionType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String defaultNewAction;
    @XmlElement(required = true)
    protected String defaultOpenAction;
    @XmlElement(required = true)
    protected String defaultEnableAction;
    @XmlElement(required = true)
    protected String defaultDisableAction;
    @XmlElement(required = true)
    protected String defaultDeleteAction;

    /**
     * Gets the value of the defaultNewAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultNewAction() {
        return defaultNewAction;
    }

    /**
     * Sets the value of the defaultNewAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultNewAction(String value) {
        this.defaultNewAction = value;
    }

    /**
     * Gets the value of the defaultOpenAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultOpenAction() {
        return defaultOpenAction;
    }

    /**
     * Sets the value of the defaultOpenAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultOpenAction(String value) {
        this.defaultOpenAction = value;
    }

    /**
     * Gets the value of the defaultEnableAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultEnableAction() {
        return defaultEnableAction;
    }

    /**
     * Sets the value of the defaultEnableAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultEnableAction(String value) {
        this.defaultEnableAction = value;
    }

    /**
     * Gets the value of the defaultDisableAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultDisableAction() {
        return defaultDisableAction;
    }

    /**
     * Sets the value of the defaultDisableAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultDisableAction(String value) {
        this.defaultDisableAction = value;
    }

    /**
     * Gets the value of the defaultDeleteAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultDeleteAction() {
        return defaultDeleteAction;
    }

    /**
     * Sets the value of the defaultDeleteAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultDeleteAction(String value) {
        this.defaultDeleteAction = value;
    }

}
