//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.17 at 10:54:36 PM CST 
//


package org.shaolin.bmdp.datamodel.pagediagram;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.shaolin.bmdp.datamodel.common.ExpressionType;


/**
 * the Logic Node, represents some business operations. Note: the OutType of LogicNodeType should be the type ConditionalOutType.  if an out's conditionalExpression is null, this out is default out.
 * 
 * <p>Java class for LogicNodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LogicNodeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bmdp.shaolin.org/datamodel/PageDiagram}WebNodeType">
 *       &lt;sequence>
 *         &lt;element name="operation" type="{http://bmdp.shaolin.org/datamodel/Common}ExpressionType"/>
 *         &lt;element name="invokeworkflowOps" type="{http://bmdp.shaolin.org/datamodel/PageDiagram}InvokeWorkflowOpsType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="needTransaction" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LogicNodeType", propOrder = {
    "operation",
    "invokeworkflowOps"
})
@XmlSeeAlso({
    StartNodeType.class
})
public class LogicNodeType
    extends WebNodeType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected ExpressionType operation;
    @XmlElement(required = true)
    protected InvokeWorkflowOpsType invokeworkflowOps;
    @XmlAttribute(name = "needTransaction")
    protected Boolean needTransaction;

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link ExpressionType }
     *     
     */
    public ExpressionType getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpressionType }
     *     
     */
    public void setOperation(ExpressionType value) {
        this.operation = value;
    }

    /**
     * Gets the value of the invokeworkflowOps property.
     * 
     * @return
     *     possible object is
     *     {@link InvokeWorkflowOpsType }
     *     
     */
    public InvokeWorkflowOpsType getInvokeworkflowOps() {
        return invokeworkflowOps;
    }

    /**
     * Sets the value of the invokeworkflowOps property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvokeWorkflowOpsType }
     *     
     */
    public void setInvokeworkflowOps(InvokeWorkflowOpsType value) {
        this.invokeworkflowOps = value;
    }

    /**
     * Gets the value of the needTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isNeedTransaction() {
        if (needTransaction == null) {
            return false;
        } else {
            return needTransaction;
        }
    }

    /**
     * Sets the value of the needTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNeedTransaction(Boolean value) {
        this.needTransaction = value;
    }

}
