//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.08 at 02:15:27 PM CST 
//


package org.shaolin.bmdp.datamodel.pagediagram;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.shaolin.bmdp.datamodel.common.ExpressionType;
import org.shaolin.bmdp.datamodel.common.TargetEntityType;


/**
 * diaply node from UIPage
 * 
 * <p>Java class for PageNodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PageNodeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bmdp.shaolin.org/datamodel/PageDiagram}WebNodeType">
 *       &lt;sequence>
 *         &lt;element name="sourceEntity" type="{http://bmdp.shaolin.org/datamodel/Common}TargetEntityType"/>
 *         &lt;element name="operation" type="{http://bmdp.shaolin.org/datamodel/Common}ExpressionType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="needTransaction" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PageNodeType", propOrder = {
    "sourceEntity",
    "operation"
})
public class PageNodeType
    extends WebNodeType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected TargetEntityType sourceEntity;
    @XmlElement(required = true)
    protected ExpressionType operation;
    @XmlAttribute(name = "needTransaction")
    protected Boolean needTransaction;

    /**
     * Gets the value of the sourceEntity property.
     * 
     * @return
     *     possible object is
     *     {@link TargetEntityType }
     *     
     */
    public TargetEntityType getSourceEntity() {
        return sourceEntity;
    }

    /**
     * Sets the value of the sourceEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetEntityType }
     *     
     */
    public void setSourceEntity(TargetEntityType value) {
        this.sourceEntity = value;
    }

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link ExpressionType }
     *     
     */
    public ExpressionType getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpressionType }
     *     
     */
    public void setOperation(ExpressionType value) {
        this.operation = value;
    }

    /**
     * Gets the value of the needTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isNeedTransaction() {
        if (needTransaction == null) {
            return false;
        } else {
            return needTransaction;
        }
    }

    /**
     * Sets the value of the needTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNeedTransaction(Boolean value) {
        this.needTransaction = value;
    }

}
