/* Generated By:JavaCC: Do not edit this line. OQLExprParserConstants.java */
package org.shaolin.javacc.sql.parser;

public interface OQLExprParserConstants {

  int EOF = 0;
  int PLUS = 5;
  int MINUS = 6;
  int MULTIPLY = 7;
  int DIVIDE = 8;
  int CONCAT = 9;
  int LARGER = 10;
  int LE = 11;
  int SMALLER = 12;
  int SE = 13;
  int EQUAL = 14;
  int NOTEQUAL = 15;
  int LIKE = 16;
  int IS = 17;
  int NULL = 18;
  int INTEGER_LITERAL = 19;
  int DECIMAL_LITERAL = 20;
  int HEX_LITERAL = 21;
  int OCTAL_LITERAL = 22;
  int FLOATING_POINT_LITERAL = 23;
  int EXPONENT = 24;
  int STRING_LITERAL = 25;
  int IDENTIFIER = 26;
  int LETTER = 27;
  int DIGIT = 28;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"||\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"=\"",
    "\"!=\"",
    "\"like\"",
    "\"is\"",
    "\"null\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\".\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"@\"",
  };

}
