//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.27 at 02:36:42 PM CST 
//


package org.shaolin.bmdp.datamodel.common;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IPropertyValueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IPropertyValueType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="pre-init-code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="post-init-code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IPropertyValueType")
@XmlSeeAlso({
    StringIPropertyType.class,
    ResourceBundleIPropertyType.class
})
public abstract class IPropertyValueType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "pre-init-code")
    protected String preInitCode;
    @XmlAttribute(name = "post-init-code")
    protected String postInitCode;

    /**
     * Gets the value of the preInitCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreInitCode() {
        return preInitCode;
    }

    /**
     * Sets the value of the preInitCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreInitCode(String value) {
        this.preInitCode = value;
    }

    /**
     * Gets the value of the postInitCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostInitCode() {
        return postInitCode;
    }

    /**
     * Sets the value of the postInitCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostInitCode(String value) {
        this.postInitCode = value;
    }

}
