//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.19 at 10:06:53 AM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bmdp.shaolin.org/datamodel/FlowDiagram", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.shaolin.bmdp.datamodel.flowdiagram;
