//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.01 at 10:34:05 PM CST 
//


package org.shaolin.bmdp.datamodel.workflow;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			
 * 
 * <p>Java class for missionNodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="missionNodeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bmdp.shaolin.org/datamodel/Workflow}generalNodeType">
 *       &lt;sequence>
 *         &lt;element name="filter" type="{http://bmdp.shaolin.org/datamodel/Workflow}destWithFilterType" minOccurs="0"/>
 *         &lt;element name="actionPage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="actionPosition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="actionProperty" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="expiredDays" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="expiredHours" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="expiredAction" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="partyType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "missionNodeType", propOrder = {
    "filter",
    "actionPage",
    "actionPosition",
    "actionProperty"
})
public class MissionNodeType
    extends GeneralNodeType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected DestWithFilterType filter;
    protected String actionPage;
    protected String actionPosition;
    protected String actionProperty;
    @XmlAttribute(name = "expiredDays")
    protected Integer expiredDays;
    @XmlAttribute(name = "expiredHours")
    protected Integer expiredHours;
    @XmlAttribute(name = "expiredAction")
    protected String expiredAction;
    @XmlAttribute(name = "partyType")
    protected String partyType;

    /**
     * Gets the value of the filter property.
     * 
     * @return
     *     possible object is
     *     {@link DestWithFilterType }
     *     
     */
    public DestWithFilterType getFilter() {
        return filter;
    }

    /**
     * Sets the value of the filter property.
     * 
     * @param value
     *     allowed object is
     *     {@link DestWithFilterType }
     *     
     */
    public void setFilter(DestWithFilterType value) {
        this.filter = value;
    }

    /**
     * Gets the value of the actionPage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionPage() {
        return actionPage;
    }

    /**
     * Sets the value of the actionPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionPage(String value) {
        this.actionPage = value;
    }

    /**
     * Gets the value of the actionPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionPosition() {
        return actionPosition;
    }

    /**
     * Sets the value of the actionPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionPosition(String value) {
        this.actionPosition = value;
    }

    /**
     * Gets the value of the actionProperty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionProperty() {
        return actionProperty;
    }

    /**
     * Sets the value of the actionProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionProperty(String value) {
        this.actionProperty = value;
    }

    /**
     * Gets the value of the expiredDays property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getExpiredDays() {
        return expiredDays;
    }

    /**
     * Sets the value of the expiredDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setExpiredDays(Integer value) {
        this.expiredDays = value;
    }

    /**
     * Gets the value of the expiredHours property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getExpiredHours() {
        return expiredHours;
    }

    /**
     * Sets the value of the expiredHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setExpiredHours(Integer value) {
        this.expiredHours = value;
    }

    /**
     * Gets the value of the expiredAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpiredAction() {
        return expiredAction;
    }

    /**
     * Sets the value of the expiredAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpiredAction(String value) {
        this.expiredAction = value;
    }

    /**
     * Gets the value of the partyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyType() {
        return partyType;
    }

    /**
     * Sets the value of the partyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyType(String value) {
        this.partyType = value;
    }

}
