//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.27 at 10:56:36 PM CST 
//


package org.shaolin.bmdp.datamodel.workflow;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.shaolin.bmdp.datamodel.workflow package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.shaolin.bmdp.datamodel.workflow
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Workflow }
     * 
     */
    public Workflow createWorkflow() {
        return new Workflow();
    }

    /**
     * Create an instance of {@link ConfType }
     * 
     */
    public ConfType createConfType() {
        return new ConfType();
    }

    /**
     * Create an instance of {@link FlowImportType }
     * 
     */
    public FlowImportType createFlowImportType() {
        return new FlowImportType();
    }

    /**
     * Create an instance of {@link FlowType }
     * 
     */
    public FlowType createFlowType() {
        return new FlowType();
    }

    /**
     * Create an instance of {@link CancelTimeoutNodeType }
     * 
     */
    public CancelTimeoutNodeType createCancelTimeoutNodeType() {
        return new CancelTimeoutNodeType();
    }

    /**
     * Create an instance of {@link ExceptionHandlerType }
     * 
     */
    public ExceptionHandlerType createExceptionHandlerType() {
        return new ExceptionHandlerType();
    }

    /**
     * Create an instance of {@link DestWithFilterType }
     * 
     */
    public DestWithFilterType createDestWithFilterType() {
        return new DestWithFilterType();
    }

    /**
     * Create an instance of {@link StartNodeType }
     * 
     */
    public StartNodeType createStartNodeType() {
        return new StartNodeType();
    }

    /**
     * Create an instance of {@link EventDestType }
     * 
     */
    public EventDestType createEventDestType() {
        return new EventDestType();
    }

    /**
     * Create an instance of {@link ProducerServiceType }
     * 
     */
    public ProducerServiceType createProducerServiceType() {
        return new ProducerServiceType();
    }

    /**
     * Create an instance of {@link DefaultTypeServiceType }
     * 
     */
    public DefaultTypeServiceType createDefaultTypeServiceType() {
        return new DefaultTypeServiceType();
    }

    /**
     * Create an instance of {@link NodeType }
     * 
     */
    public NodeType createNodeType() {
        return new NodeType();
    }

    /**
     * Create an instance of {@link JoinNodeType }
     * 
     */
    public JoinNodeType createJoinNodeType() {
        return new JoinNodeType();
    }

    /**
     * Create an instance of {@link ConditionNodeType }
     * 
     */
    public ConditionNodeType createConditionNodeType() {
        return new ConditionNodeType();
    }

    /**
     * Create an instance of {@link DestType }
     * 
     */
    public DestType createDestType() {
        return new DestType();
    }

    /**
     * Create an instance of {@link JoinExpressionType }
     * 
     */
    public JoinExpressionType createJoinExpressionType() {
        return new JoinExpressionType();
    }

    /**
     * Create an instance of {@link ExceptionType }
     * 
     */
    public ExceptionType createExceptionType() {
        return new ExceptionType();
    }

    /**
     * Create an instance of {@link EndNodeType }
     * 
     */
    public EndNodeType createEndNodeType() {
        return new EndNodeType();
    }

    /**
     * Create an instance of {@link SplitNodeType }
     * 
     */
    public SplitNodeType createSplitNodeType() {
        return new SplitNodeType();
    }

    /**
     * Create an instance of {@link FlowConfType }
     * 
     */
    public FlowConfType createFlowConfType() {
        return new FlowConfType();
    }

    /**
     * Create an instance of {@link HandlerType }
     * 
     */
    public HandlerType createHandlerType() {
        return new HandlerType();
    }

    /**
     * Create an instance of {@link ChildFlowNodeType }
     * 
     */
    public ChildFlowNodeType createChildFlowNodeType() {
        return new ChildFlowNodeType();
    }

    /**
     * Create an instance of {@link SessionServiceType }
     * 
     */
    public SessionServiceType createSessionServiceType() {
        return new SessionServiceType();
    }

    /**
     * Create an instance of {@link TimeoutNodeType }
     * 
     */
    public TimeoutNodeType createTimeoutNodeType() {
        return new TimeoutNodeType();
    }

    /**
     * Create an instance of {@link MissionNodeType }
     * 
     */
    public MissionNodeType createMissionNodeType() {
        return new MissionNodeType();
    }

    /**
     * Create an instance of {@link GeneralNodeType }
     * 
     */
    public GeneralNodeType createGeneralNodeType() {
        return new GeneralNodeType();
    }

}
