//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.27 at 10:56:36 PM CST 
//


package org.shaolin.bmdp.datamodel.workflow;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				A timeout-node can configure a timeout interval,
 * 				and a destination node to handle timeout. The waiting event will be
 * 				passed to the timeout destination when over time.
 * 			
 * 
 * <p>Java class for timeoutNodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="timeoutNodeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bmdp.shaolin.org/datamodel/Workflow}nodeType">
 *       &lt;sequence>
 *         &lt;element name="timeout-dest" type="{http://bmdp.shaolin.org/datamodel/Workflow}destType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "timeoutNodeType", propOrder = {
    "timeoutDest"
})
public class TimeoutNodeType
    extends NodeType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "timeout-dest")
    protected DestType timeoutDest;

    /**
     * Gets the value of the timeoutDest property.
     * 
     * @return
     *     possible object is
     *     {@link DestType }
     *     
     */
    public DestType getTimeoutDest() {
        return timeoutDest;
    }

    /**
     * Sets the value of the timeoutDest property.
     * 
     * @param value
     *     allowed object is
     *     {@link DestType }
     *     
     */
    public void setTimeoutDest(DestType value) {
        this.timeoutDest = value;
    }

}
