//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.27 at 02:34:46 PM CST 
//


package org.shaolin.bmdp.datamodel.bediagram;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.shaolin.bmdp.datamodel.common.MetaDataType;
import org.shaolin.bmdp.datamodel.common.TargetEntityType;


/**
 * <p>Java class for EntityRelationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EntityRelationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bmdp.shaolin.org/datamodel/Common}MetaDataType">
 *       &lt;sequence>
 *         &lt;element name="entity" type="{http://bmdp.shaolin.org/datamodel/Common}TargetEntityType"/>
 *         &lt;element name="entity2" type="{http://bmdp.shaolin.org/datamodel/Common}TargetEntityType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="refedName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="refedPriority" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="type" use="required" type="{http://bmdp.shaolin.org/datamodel/BEDiagram}RelationTypeType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EntityRelationType", propOrder = {
    "entity",
    "entity2"
})
public class EntityRelationType
    extends MetaDataType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected TargetEntityType entity;
    @XmlElement(required = true)
    protected TargetEntityType entity2;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "priority")
    protected Integer priority;
    @XmlAttribute(name = "refedName")
    protected String refedName;
    @XmlAttribute(name = "refedPriority")
    protected Integer refedPriority;
    @XmlAttribute(name = "type", required = true)
    protected RelationTypeType type;

    /**
     * Gets the value of the entity property.
     * 
     * @return
     *     possible object is
     *     {@link TargetEntityType }
     *     
     */
    public TargetEntityType getEntity() {
        return entity;
    }

    /**
     * Sets the value of the entity property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetEntityType }
     *     
     */
    public void setEntity(TargetEntityType value) {
        this.entity = value;
    }

    /**
     * Gets the value of the entity2 property.
     * 
     * @return
     *     possible object is
     *     {@link TargetEntityType }
     *     
     */
    public TargetEntityType getEntity2() {
        return entity2;
    }

    /**
     * Sets the value of the entity2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetEntityType }
     *     
     */
    public void setEntity2(TargetEntityType value) {
        this.entity2 = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPriority(Integer value) {
        this.priority = value;
    }

    /**
     * Gets the value of the refedName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefedName() {
        return refedName;
    }

    /**
     * Sets the value of the refedName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefedName(String value) {
        this.refedName = value;
    }

    /**
     * Gets the value of the refedPriority property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRefedPriority() {
        return refedPriority;
    }

    /**
     * Sets the value of the refedPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRefedPriority(Integer value) {
        this.refedPriority = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link RelationTypeType }
     *     
     */
    public RelationTypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationTypeType }
     *     
     */
    public void setType(RelationTypeType value) {
        this.type = value;
    }

}
