//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.27 at 02:34:46 PM CST 
//


package org.shaolin.bmdp.datamodel.bediagram;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.shaolin.bmdp.datamodel.bediagram package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.shaolin.bmdp.datamodel.bediagram
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BEDiagram }
     * 
     */
    public BEDiagram createBEDiagram() {
        return new BEDiagram();
    }

    /**
     * Create an instance of {@link BusinessEntityType }
     * 
     */
    public BusinessEntityType createBusinessEntityType() {
        return new BusinessEntityType();
    }

    /**
     * Create an instance of {@link ConstantEntityType }
     * 
     */
    public ConstantEntityType createConstantEntityType() {
        return new ConstantEntityType();
    }

    /**
     * Create an instance of {@link ConstantValueType }
     * 
     */
    public ConstantValueType createConstantValueType() {
        return new ConstantValueType();
    }

    /**
     * Create an instance of {@link DummyFieldType }
     * 
     */
    public DummyFieldType createDummyFieldType() {
        return new DummyFieldType();
    }

    /**
     * Create an instance of {@link JavaObjRefType }
     * 
     */
    public JavaObjRefType createJavaObjRefType() {
        return new JavaObjRefType();
    }

    /**
     * Create an instance of {@link EntityRelationType }
     * 
     */
    public EntityRelationType createEntityRelationType() {
        return new EntityRelationType();
    }

    /**
     * Create an instance of {@link BEPrimitiveType }
     * 
     */
    public BEPrimitiveType createBEPrimitiveType() {
        return new BEPrimitiveType();
    }

    /**
     * Create an instance of {@link DateTimeType }
     * 
     */
    public DateTimeType createDateTimeType() {
        return new DateTimeType();
    }

    /**
     * Create an instance of {@link BEComplexType }
     * 
     */
    public BEComplexType createBEComplexType() {
        return new BEComplexType();
    }

    /**
     * Create an instance of {@link BEObjRefType }
     * 
     */
    public BEObjRefType createBEObjRefType() {
        return new BEObjRefType();
    }

    /**
     * Create an instance of {@link MemberWebServiceMappingType }
     * 
     */
    public MemberWebServiceMappingType createMemberWebServiceMappingType() {
        return new MemberWebServiceMappingType();
    }

    /**
     * Create an instance of {@link IntType }
     * 
     */
    public IntType createIntType() {
        return new IntType();
    }

    /**
     * Create an instance of {@link FileType }
     * 
     */
    public FileType createFileType() {
        return new FileType();
    }

    /**
     * Create an instance of {@link CEObjRefType }
     * 
     */
    public CEObjRefType createCEObjRefType() {
        return new CEObjRefType();
    }

    /**
     * Create an instance of {@link DoubleType }
     * 
     */
    public DoubleType createDoubleType() {
        return new DoubleType();
    }

    /**
     * Create an instance of {@link RelationConstraintType }
     * 
     */
    public RelationConstraintType createRelationConstraintType() {
        return new RelationConstraintType();
    }

    /**
     * Create an instance of {@link BEMapType }
     * 
     */
    public BEMapType createBEMapType() {
        return new BEMapType();
    }

    /**
     * Create an instance of {@link PersistentConfigType }
     * 
     */
    public PersistentConfigType createPersistentConfigType() {
        return new PersistentConfigType();
    }

    /**
     * Create an instance of {@link RelationKeyType }
     * 
     */
    public RelationKeyType createRelationKeyType() {
        return new RelationKeyType();
    }

    /**
     * Create an instance of {@link BESetType }
     * 
     */
    public BESetType createBESetType() {
        return new BESetType();
    }

    /**
     * Create an instance of {@link LongType }
     * 
     */
    public LongType createLongType() {
        return new LongType();
    }

    /**
     * Create an instance of {@link ExternalReferenceType }
     * 
     */
    public ExternalReferenceType createExternalReferenceType() {
        return new ExternalReferenceType();
    }

    /**
     * Create an instance of {@link StringType }
     * 
     */
    public StringType createStringType() {
        return new StringType();
    }

    /**
     * Create an instance of {@link BEListType }
     * 
     */
    public BEListType createBEListType() {
        return new BEListType();
    }

    /**
     * Create an instance of {@link BinaryType }
     * 
     */
    public BinaryType createBinaryType() {
        return new BinaryType();
    }

    /**
     * Create an instance of {@link BEType }
     * 
     */
    public BEType createBEType() {
        return new BEType();
    }

    /**
     * Create an instance of {@link ReferenceObjectType }
     * 
     */
    public ReferenceObjectType createReferenceObjectType() {
        return new ReferenceObjectType();
    }

    /**
     * Create an instance of {@link TimeType }
     * 
     */
    public TimeType createTimeType() {
        return new TimeType();
    }

    /**
     * Create an instance of {@link MemberType }
     * 
     */
    public MemberType createMemberType() {
        return new MemberType();
    }

    /**
     * Create an instance of {@link ValidatorConfigType }
     * 
     */
    public ValidatorConfigType createValidatorConfigType() {
        return new ValidatorConfigType();
    }

    /**
     * Create an instance of {@link EntityNameWebServiceMappingType }
     * 
     */
    public EntityNameWebServiceMappingType createEntityNameWebServiceMappingType() {
        return new EntityNameWebServiceMappingType();
    }

    /**
     * Create an instance of {@link BooleanType }
     * 
     */
    public BooleanType createBooleanType() {
        return new BooleanType();
    }

    /**
     * Create an instance of {@link SearchMethodType }
     * 
     */
    public SearchMethodType createSearchMethodType() {
        return new SearchMethodType();
    }

}
