//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.27 at 02:34:46 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bmdp.shaolin.org/datamodel/BEDiagram", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.shaolin.bmdp.datamodel.bediagram;
