//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.27 at 02:36:42 PM CST 
//


package org.shaolin.bmdp.datamodel.rdbdiagram;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JoinTableType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JoinTableType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="srcTable" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="srcPKColumn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tarTable" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tarPKColumn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JoinTableType")
public class JoinTableType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "srcTable", required = true)
    protected String srcTable;
    @XmlAttribute(name = "srcPKColumn", required = true)
    protected String srcPKColumn;
    @XmlAttribute(name = "tarTable", required = true)
    protected String tarTable;
    @XmlAttribute(name = "tarPKColumn", required = true)
    protected String tarPKColumn;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the srcTable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcTable() {
        return srcTable;
    }

    /**
     * Sets the value of the srcTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcTable(String value) {
        this.srcTable = value;
    }

    /**
     * Gets the value of the srcPKColumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcPKColumn() {
        return srcPKColumn;
    }

    /**
     * Sets the value of the srcPKColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcPKColumn(String value) {
        this.srcPKColumn = value;
    }

    /**
     * Gets the value of the tarTable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarTable() {
        return tarTable;
    }

    /**
     * Sets the value of the tarTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarTable(String value) {
        this.tarTable = value;
    }

    /**
     * Gets the value of the tarPKColumn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarPKColumn() {
        return tarPKColumn;
    }

    /**
     * Sets the value of the tarPKColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarPKColumn(String value) {
        this.tarPKColumn = value;
    }

}
