//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.27 at 02:36:42 PM CST 
//


package org.shaolin.bmdp.datamodel.rdbdiagram;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * List mapping
 * 
 * <p>Java class for ListFieldMappingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListFieldMappingType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bmdp.shaolin.org/datamodel/RDBDiagram}FieldMappingType">
 *       &lt;attribute name="associationName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="collectionElement" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mappingType" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="One-to-One"/>
 *             &lt;enumeration value="One-to-Many"/>
 *             &lt;enumeration value="Many-to-Many"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListFieldMappingType")
public class ListFieldMappingType
    extends FieldMappingType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "associationName", required = true)
    protected String associationName;
    @XmlAttribute(name = "collectionElement", required = true)
    protected String collectionElement;
    @XmlAttribute(name = "mappingType", required = true)
    protected String mappingType;

    /**
     * Gets the value of the associationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssociationName() {
        return associationName;
    }

    /**
     * Sets the value of the associationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssociationName(String value) {
        this.associationName = value;
    }

    /**
     * Gets the value of the collectionElement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollectionElement() {
        return collectionElement;
    }

    /**
     * Sets the value of the collectionElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollectionElement(String value) {
        this.collectionElement = value;
    }

    /**
     * Gets the value of the mappingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMappingType() {
        return mappingType;
    }

    /**
     * Sets the value of the mappingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMappingType(String value) {
        this.mappingType = value;
    }

}
