//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.27 at 02:36:42 PM CST 
//


package org.shaolin.bmdp.datamodel.rdbdiagram;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.shaolin.bmdp.datamodel.common.ExpressionType;
import org.shaolin.bmdp.datamodel.common.VariableType;


/**
 * SQL search query definition.
 * 
 * <p>Java class for SearchQueryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchQueryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="searchResult" type="{http://bmdp.shaolin.org/datamodel/Common}VariableType"/>
 *         &lt;element name="fromData" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://bmdp.shaolin.org/datamodel/Common}VariableType">
 *                 &lt;sequence>
 *                   &lt;element name="customerRDBName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="searchResultMapping" type="{http://bmdp.shaolin.org/datamodel/RDBDiagram}SearchResultMappingType"/>
 *         &lt;element name="linkMapping" type="{http://bmdp.shaolin.org/datamodel/RDBDiagram}LinkConditionMappingType"/>
 *         &lt;element name="searchConditionMapping" type="{http://bmdp.shaolin.org/datamodel/RDBDiagram}SearchConditionMappingType"/>
 *         &lt;element name="orderBy" type="{http://bmdp.shaolin.org/datamodel/RDBDiagram}OrderingType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="postSearch" type="{http://bmdp.shaolin.org/datamodel/Common}ExpressionType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="timeoutSeconds" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="isDistinct" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="queryName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchQueryType", propOrder = {
    "searchResult",
    "fromDatas",
    "searchResultMapping",
    "linkMapping",
    "searchConditionMapping",
    "orderBies",
    "postSearch"
})
public class SearchQueryType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected VariableType searchResult;
    @XmlElement(name = "fromData", required = true)
    protected List<SearchQueryType.FromData> fromDatas;
    @XmlElement(required = true)
    protected SearchResultMappingType searchResultMapping;
    @XmlElement(required = true)
    protected LinkConditionMappingType linkMapping;
    @XmlElement(required = true)
    protected SearchConditionMappingType searchConditionMapping;
    @XmlElement(name = "orderBy")
    protected List<OrderingType> orderBies;
    @XmlElement(required = true)
    protected ExpressionType postSearch;
    @XmlAttribute(name = "timeoutSeconds")
    protected Integer timeoutSeconds;
    @XmlAttribute(name = "isDistinct")
    protected Boolean isDistinct;
    @XmlAttribute(name = "queryName", required = true)
    protected String queryName;

    /**
     * Gets the value of the searchResult property.
     * 
     * @return
     *     possible object is
     *     {@link VariableType }
     *     
     */
    public VariableType getSearchResult() {
        return searchResult;
    }

    /**
     * Sets the value of the searchResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariableType }
     *     
     */
    public void setSearchResult(VariableType value) {
        this.searchResult = value;
    }

    /**
     * Gets the value of the fromDatas property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fromDatas property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFromDatas().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SearchQueryType.FromData }
     * 
     * 
     */
    public List<SearchQueryType.FromData> getFromDatas() {
        if (fromDatas == null) {
            fromDatas = new ArrayList<SearchQueryType.FromData>();
        }
        return this.fromDatas;
    }

    /**
     * Gets the value of the searchResultMapping property.
     * 
     * @return
     *     possible object is
     *     {@link SearchResultMappingType }
     *     
     */
    public SearchResultMappingType getSearchResultMapping() {
        return searchResultMapping;
    }

    /**
     * Sets the value of the searchResultMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchResultMappingType }
     *     
     */
    public void setSearchResultMapping(SearchResultMappingType value) {
        this.searchResultMapping = value;
    }

    /**
     * Gets the value of the linkMapping property.
     * 
     * @return
     *     possible object is
     *     {@link LinkConditionMappingType }
     *     
     */
    public LinkConditionMappingType getLinkMapping() {
        return linkMapping;
    }

    /**
     * Sets the value of the linkMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkConditionMappingType }
     *     
     */
    public void setLinkMapping(LinkConditionMappingType value) {
        this.linkMapping = value;
    }

    /**
     * Gets the value of the searchConditionMapping property.
     * 
     * @return
     *     possible object is
     *     {@link SearchConditionMappingType }
     *     
     */
    public SearchConditionMappingType getSearchConditionMapping() {
        return searchConditionMapping;
    }

    /**
     * Sets the value of the searchConditionMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchConditionMappingType }
     *     
     */
    public void setSearchConditionMapping(SearchConditionMappingType value) {
        this.searchConditionMapping = value;
    }

    /**
     * Gets the value of the orderBies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderBies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderBies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderingType }
     * 
     * 
     */
    public List<OrderingType> getOrderBies() {
        if (orderBies == null) {
            orderBies = new ArrayList<OrderingType>();
        }
        return this.orderBies;
    }

    /**
     * Gets the value of the postSearch property.
     * 
     * @return
     *     possible object is
     *     {@link ExpressionType }
     *     
     */
    public ExpressionType getPostSearch() {
        return postSearch;
    }

    /**
     * Sets the value of the postSearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpressionType }
     *     
     */
    public void setPostSearch(ExpressionType value) {
        this.postSearch = value;
    }

    /**
     * Gets the value of the timeoutSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getTimeoutSeconds() {
        if (timeoutSeconds == null) {
            return  0;
        } else {
            return timeoutSeconds;
        }
    }

    /**
     * Sets the value of the timeoutSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTimeoutSeconds(Integer value) {
        this.timeoutSeconds = value;
    }

    /**
     * Gets the value of the isDistinct property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsDistinct() {
        if (isDistinct == null) {
            return true;
        } else {
            return isDistinct;
        }
    }

    /**
     * Sets the value of the isDistinct property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsDistinct(Boolean value) {
        this.isDistinct = value;
    }

    /**
     * Gets the value of the queryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueryName() {
        return queryName;
    }

    /**
     * Sets the value of the queryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueryName(String value) {
        this.queryName = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://bmdp.shaolin.org/datamodel/Common}VariableType">
     *       &lt;sequence>
     *         &lt;element name="customerRDBName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "customerRDBName"
    })
    public static class FromData
        extends VariableType
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        protected String customerRDBName;

        /**
         * Gets the value of the customerRDBName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustomerRDBName() {
            return customerRDBName;
        }

        /**
         * Sets the value of the customerRDBName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustomerRDBName(String value) {
            this.customerRDBName = value;
        }

    }

}
