//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.27 at 02:36:42 PM CST 
//


package org.shaolin.bmdp.datamodel.rdbdiagram;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.shaolin.bmdp.datamodel.common.ExpressionType;
import org.shaolin.bmdp.datamodel.common.VariableType;


/**
 * <p>Java class for SubQueryMappingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubQueryMappingType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bmdp.shaolin.org/datamodel/RDBDiagram}ConditionFieldMappingType">
 *       &lt;sequence>
 *         &lt;element name="operator" type="{http://bmdp.shaolin.org/datamodel/RDBDiagram}OperatorType"/>
 *         &lt;element name="selectedDataFieldPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fromData" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://bmdp.shaolin.org/datamodel/Common}VariableType">
 *                 &lt;sequence>
 *                   &lt;element name="customerRDBName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="linkMapping" type="{http://bmdp.shaolin.org/datamodel/RDBDiagram}LinkConditionMappingType"/>
 *         &lt;element name="fieldMapping" type="{http://bmdp.shaolin.org/datamodel/RDBDiagram}FilterMappingType" maxOccurs="unbounded"/>
 *         &lt;element name="condition" type="{http://bmdp.shaolin.org/datamodel/Common}ExpressionType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isDistinct" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubQueryMappingType", propOrder = {
    "operator",
    "selectedDataFieldPath",
    "fromDatas",
    "linkMapping",
    "fieldMappings",
    "condition"
})
public class SubQueryMappingType
    extends ConditionFieldMappingType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected OperatorType operator;
    protected String selectedDataFieldPath;
    @XmlElement(name = "fromData", required = true)
    protected List<SubQueryMappingType.FromData> fromDatas;
    @XmlElement(required = true)
    protected LinkConditionMappingType linkMapping;
    @XmlElement(name = "fieldMapping", required = true)
    protected List<FilterMappingType> fieldMappings;
    protected ExpressionType condition;
    @XmlAttribute(name = "isDistinct")
    protected Boolean isDistinct;

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link OperatorType }
     *     
     */
    public OperatorType getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperatorType }
     *     
     */
    public void setOperator(OperatorType value) {
        this.operator = value;
    }

    /**
     * Gets the value of the selectedDataFieldPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelectedDataFieldPath() {
        return selectedDataFieldPath;
    }

    /**
     * Sets the value of the selectedDataFieldPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelectedDataFieldPath(String value) {
        this.selectedDataFieldPath = value;
    }

    /**
     * Gets the value of the fromDatas property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fromDatas property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFromDatas().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubQueryMappingType.FromData }
     * 
     * 
     */
    public List<SubQueryMappingType.FromData> getFromDatas() {
        if (fromDatas == null) {
            fromDatas = new ArrayList<SubQueryMappingType.FromData>();
        }
        return this.fromDatas;
    }

    /**
     * Gets the value of the linkMapping property.
     * 
     * @return
     *     possible object is
     *     {@link LinkConditionMappingType }
     *     
     */
    public LinkConditionMappingType getLinkMapping() {
        return linkMapping;
    }

    /**
     * Sets the value of the linkMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkConditionMappingType }
     *     
     */
    public void setLinkMapping(LinkConditionMappingType value) {
        this.linkMapping = value;
    }

    /**
     * Gets the value of the fieldMappings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fieldMappings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFieldMappings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FilterMappingType }
     * 
     * 
     */
    public List<FilterMappingType> getFieldMappings() {
        if (fieldMappings == null) {
            fieldMappings = new ArrayList<FilterMappingType>();
        }
        return this.fieldMappings;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link ExpressionType }
     *     
     */
    public ExpressionType getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpressionType }
     *     
     */
    public void setCondition(ExpressionType value) {
        this.condition = value;
    }

    /**
     * Gets the value of the isDistinct property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsDistinct() {
        if (isDistinct == null) {
            return false;
        } else {
            return isDistinct;
        }
    }

    /**
     * Sets the value of the isDistinct property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsDistinct(Boolean value) {
        this.isDistinct = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://bmdp.shaolin.org/datamodel/Common}VariableType">
     *       &lt;sequence>
     *         &lt;element name="customerRDBName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "customerRDBName"
    })
    public static class FromData
        extends VariableType
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        protected String customerRDBName;

        /**
         * Gets the value of the customerRDBName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustomerRDBName() {
            return customerRDBName;
        }

        /**
         * Sets the value of the customerRDBName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustomerRDBName(String value) {
            this.customerRDBName = value;
        }

    }

}
