/*
 *
 * This file is automatically generated on Thu Jun 04 22:37:13 CST 2015
 */

    
package org.shaolin.bmdp.coordinator.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;



/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public interface INotification 
    extends IPersistentEntity, IExtensibleEntity
{
    public final static String ENTITY_NAME = "org.shaolin.bmdp.coordinator.be.Notification";
    
 
    /**
     *  get id
     *
     *  @return id
     */
    public long getId();

    /**
     *  get partyId
     *
     *  @return partyId
     */
    public long getPartyId();

    /**
     *  get subject
     *
     *  @return subject
     */
    public java.lang.String getSubject();

    /**
     *  get description
     *
     *  @return description
     */
    public java.lang.String getDescription();

    /**
     *  set id
     */
    public void setId(long id);

    /**
     *  set partyId
     */
    public void setPartyId(long partyId);

    /**
     *  set subject
     */
    public void setSubject(java.lang.String subject);

    /**
     *  set description
     */
    public void setDescription(java.lang.String description);


}

        